* Installation Instructions

  Installing guile-2d is rather easy (but not easy enough) if you are
  on a GNU/Linux system. Currently, only installation instructions for
  Debian are provided, but the non-apt commands should work without
  any modifications on any GNU/Linux distro.

  This installation guide assumes that you have the GNU build system
  (automake, autoconf, texinfo, pkg-config) and git installed.

** Install dependencies

*** Guile

    *Debian*

    #+BEGIN_SRC sh
      sudo apt-get install guile-2.0-dev
    #+END_SRC

    This assumes that the version of Debian you are running has Guile
    2.0.11.

    *Gentoo*

    #+BEGIN_SRC sh
      sudo emerge ">=dev-scheme/guile-2.0.11"
    #+END_SRC

    Check the versions available to you with =sudo apt-cache show guile-2.0-dev=.

*** SDL
    SDL is a very popular, cross-platform game library.

    *Debian*

     #+BEGIN_SRC sh
       sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
     #+END_SRC

    *Gentoo*

    #+BEGIN_SRC sh
      sudo emerge libsdl sdl-image sdl-mixer sdl-ttf
    #+END_SRC

*** Freeimage

    Freeimage is to used to load textures. Make sure that your distro
    provides at least version 3.14.

    *Debian*

    #+BEGIN_SRC sh
      sudo apt-get install libfreeimage-dev
    #+END_SRC

    *Gentoo*

    #+BEGIN_SRC sh
      sudo emerge freeimage
    #+END_SRC

*** guile-sdl

    guile-sdl is the GNU Guile wrapper for SDL.

    Grab the latest release tarball from http://www.gnu.org/software/guile-sdl/.

    *Source*

    #+BEGIN_SRC sh
      tar xf guile-sdl-<version>.tar.xz
      cd guile-sdl-<version>/
      ./configure --prefix=/usr
      make
      sudo make install
    #+END_SRC

    Note: guile-sdl is currently broken on OS X. Please see this issue
    for more information:
    https://github.com/davexunit/guile-2d/issues/2

*** guile-opengl

    *Source*

    guile-opengl is the GNU Guile wrapper for OpenGL.

    Grab the latest release tarball from http://ftp.gnu.org/gnu/guile-opengl/.

    #+BEGIN_SRC sh
      tar -xvf guile-opengl-<version>.tar.gz
      cd guile-opengl/
      ./configure --prefix=/usr
      make
      sudo make install
    #+END_SRC

** Install guile-2d

   Once the dependencies have been installed, installing guile-2d is
   pretty straightforward.

   *GNU/Linux*

   #+BEGIN_SRC sh
     git clone https://github.com/davexunit/guile-2d.git
     cd guile-2d/
     ./autogen.sh
     ./configure --prefix=/usr
     make
     sudo make install
   #+END_SRC

*** Install to /usr/local

   If you want to avoid installing to /usr, you can build like this:

   #+BEGIN_SRC sh
     ./configure
     GUILE_LOAD_PATH=/usr/local/share/guile/site/2.0/:/usr/local/share/guile/site/ make
     sudo make install
   #+END_SRC

   Then use the same call to run guile:

   #+BEGIN_SRC
     GUILE_LOAD_PATH=/usr/local/share/guile/site/2.0/:/usr/local/share/guile/site/ guile
   #+END_SRC
