#! /usr/bin/guile \
-L . -s
!#

;;; Sly
;;; Copyright (C) 2014 David Thompson <dthompson2@worcester.edu>
;;;
;;; This program is free software: you can redistribute it and/or
;;; modify it under the terms of the GNU General Public License as
;;; published by the Free Software Foundation, either version 3 of the
;;; License, or (at your option) any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see
;;; <http://www.gnu.org/licenses/>.

;; Include almost every Sly module for convenience.
(use-modules (sly agenda)
             (sly audio)
             (sly color)
             (sly coroutine)
             (sly font)
             (sly fps)
             (sly game)
             (sly keyboard)
             (sly mouse)
             (sly rect)
             (sly signal)
             (sly sprite)
             (sly texture)
             (sly transform)
             (sly vector)
             (sly window)
             (sly scene)
             (sly camera)
             (sly repl))

(open-window)
(start-sly-repl)

(add-hook! window-close-hook stop-game-loop)

(display "Welcome to the Sly sandbox.  Happy hacking!\n")

(define-signal simple-scene
  (scene-root
   (scene-node
    (position #(100 100))
    (uniforms `(("color" ,white)))
    (children (list (load-sprite "examples/images/p1_front.png"))))))

(define-signal camera
  (orthographic-camera simple-scene 640 480))

(with-window (make-window #:title "Sly Sandbox")
  (start-game-loop camera))

(display "Bye!\n")

;;; Local Variables:
;;; compile-command: "./pre-inst-env sandbox"
;;; End:
